#!/usr/bin/env sh


export DISPLAY=:0
export XAUTHORITY=~/.Xauthority

out_lb=/tmp/competitions_lb.txt

while read line; do
    d=$(date -d $(echo $line | cut -d' ' -f 1) +"%b %-d, %Y, %I:%M %P %Z")
    url=$(echo $line | cut -d' ' -f 2)
    if [ "${1}" = "show" ]; then
        er=0
    else
        cookies=$(echo $line | cut -d' ' -f 3-)
        python $HOME/.local/bin/parse-leaderbord.py "${url}" "${cookies}" "${out_lb}"
        er=$?
    fi

    msg=""
    [ "${er}" -eq -1 ] && msg="error"
    [ "${er}" -eq  0 ] && msg="$(jq -r "select(.url==\"${url}\") | .body" "${out_lb}")"
    [ "${er}" -eq  2 ] && msg="check cookies"

    [ -n "${msg}" ] \
        && dunstify \
            -a "kaggle" \
            -t 0 \
            "${d} ${url}" \
            "${msg}" \

done < $HOME/.local/share/competition_links.txt
