#!/usr/bin/env sh

# Script to notify user for new mails.
# Crontab ex:
# */5 * * * * $HOME/.local/bin/mbsync-notify [acc_name]

#`notify-send` requires connection to DBUS_SESSION_BUS_ADDRESS
# and one way is to export display and use X server authority cookies thru .Xauthority
# see here https://askubuntu.com/questions/298608/notify-send-doesnt-work-from-crontab
export DISPLAY=:0
export XAUTHORITY=$HOME/.Xauthority

# do not duplicate
killall -9 mbsync &> /dev/null

#run mbsync once for all accs with named configs file, with quiet interface
# or specify account name as argument and define separate cron tasks for each acc
if [ -n $1 ]
then
  acc=$1
else
  acc=
fi
/usr/bin/mbsync -c $HOME/.mbsyncrc -a $acc -q
/usr/bin/notmuch new

#count new mail for every maildir, only in INBOX
# since there are maildirs/accounts in a format `~/.local/share/email/account1/subacc1`,
# `~/.local/share/email/account1/subacc2`, `~/.local/share/email/account2/subacc1` etc
# there should be such an expansion
maildirnew="$HOME/.local/share/email/*/INBOX/new/"
new="$(find $maildirnew -type f | wc -l)"

#count old mail for every maildir
maildirold="$HOME/.local/share/email/*/INBOX/cur/"
old="$(find $maildirold -type f | wc -l)"

if [ $new -gt 0 ]; then
  /usr/bin/dunstify -a "mbsync" "new mail!" "new: $new old: $old"
fi
