#!/usr/bin/env sh

# change monitor configs


MODE="${1}"


case "${MODE}" in
    fhd)
        xrandr \
            --output eDP-1 --auto --pos 0x964 \
            --output HDMI-1 --primary --mode 1920x1080 --auto --pos 1366x0 \

        ;;
    4k)
        xrandr \
            --output eDP-1 --auto --pos 2560x1200 \
            --output HDMI-1 --primary --mode 2560x1600 --auto --pos 0x0 \

        ;;
    off)
        xrandr \
            --output eDP-1 --off \

        ;;
    *)
        xrandr \
            --output eDP-1 --primary --auto \
            --output HDMI-1 --off \

        ;;
esac
